In [139]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Part-1: Data Exploration and Pre-processing

# 1) load dataset

In [143]:
data = pd.read_csv(r"D:\ml-project\1768299091977-ML Linear Regression Home Price Prediction & Analysis Project  Resource16932049360.txt")

In [145]:
data

,Suburb,Address,Rooms,Type,Price,Method,SellerG,Date,Distance,Postcode,...,Bathroom,Car,Landsize,BuildingArea,YearBuilt,CouncilArea,Lattitude,Longtitude,Regionname,Propertycount
0,Abbotsford,68 Studley St,2,h,NaN,SS,Jellis,03/09/2016,2.5,3067.0,...,1.0,1.0,126.0,NaN,NaN,Yarra City Council,-37.80140,144.99580,Northern Metropolitan,4019.0
1,Abbotsford,85 Turner St,2,h,1480000.0,S,Biggin,03/12/2016,2.5,3067.0,...,1.0,1.0,202.0,NaN,NaN,Yarra City Council,-37.79960,144.99840,Northern Metropolitan,4019.0
2,Abbotsford,25 Bloomburg St,2,h,1035000.0,S,Biggin,04/02/2016,2.5,3067.0,...,1.0,0.0,156.0,79.0,1900.0,Yarra City Council,-37.80790,144.99340,Northern Metropolitan,4019.0
3,Abbotsford,18/659 Victoria St,3,u,NaN,VB,Rounds,04/02/2016,2.5,3067.0,...,2.0,1.0,0.0,NaN,NaN,Yarra City Council,-37.81140,145.01160,Northern Metropolitan,4019.0
4,Abbotsford,5 Charles St,3,h,1465000.0,SP,Biggin,04/03/2017,2.5,3067.0,...,2.0,0.0,134.0,150.0,1900.0,Yarra City Council,-37.80930,144.99440,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,13 Burns St,4,h,1480000.0,PI,Jas,24/02/2018,6.3,3013.0,...,1.0,3.0,593.0,NaN,NaN,Maribyrnong City Council,-37.81053,144.88467,Western Metropolitan,6543.0
34853,Yarraville,29A Murray St,2,h,888000.0,SP,Sweeney,24/02/2018,6.3,3013.0,...,2.0,1.0,98.0,104.0,2018.0,Maribyrnong City Council,-37.81551,144.88826,Western Metropolitan,6543.0
34854,Yarraville,147A Severn St,2,t,705000.0,S,Jas,24/02/2018,6.3,3013.0,...,1.0,2.0,220.0,120.0,2000.0,Maribyrnong City Council,-37.82286,144.87856,Western Metropolitan,6543.0
34855,Yarraville,12/37 Stephen St,3,h,1140000.0,SP,hockingstuart,24/02/2018,6.3,3013.0,...,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,NaN,NaN,Western Metropolitan,6543.0
34856,Yarraville,3 Tarrengower St,2,h,1020000.0,PI,RW,24/02/2018,6.3,3013.0,...,1.0,0.0,250.0,103.0,1930.0,Maribyrnong City Council,-37.81810,144.89351,Western Metropolitan,6543.0

# 2) Print all the column names

In [148]:
data.columns

Index(['Suburb', 'Address', 'Rooms', 'Type', 'Price', 'Method', 'SellerG',
       'Date', 'Distance', 'Postcode', 'Bedroom2', 'Bathroom', 'Car',
       'Landsize', 'BuildingArea', 'YearBuilt', 'CouncilArea', 'Lattitude',
       'Longtitude', 'Regionname', 'Propertycount'],
      dtype='object')

# 3) Describe the data

In [151]:
data.describe()

,Rooms,Price,Distance,Postcode,Bedroom2,Bathroom,Car,Landsize,BuildingArea,YearBuilt,Lattitude,Longtitude,Propertycount
count,34857.000000,2.724700e+04,34856.000000,34856.000000,26640.000000,26631.000000,26129.000000,23047.000000,13742.00000,15551.000000,26881.000000,26881.000000,34854.000000
mean,3.031012,1.050173e+06,11.184929,3116.062859,3.084647,1.624798,1.728845,593.598993,160.25640,1965.289885,-37.810634,145.001851,7572.888306
std,0.969933,6.414671e+05,6.788892,109.023903,0.980690,0.724212,1.010771,3398.841946,401.26706,37.328178,0.090279,0.120169,4428.090313
min,1.000000,8.500000e+04,0.000000,3000.000000,0.000000,0.000000,0.000000,0.000000,0.00000,1196.000000,-38.190430,144.423790,83.000000
25%,2.000000,6.350000e+05,6.400000,3051.000000,2.000000,1.000000,1.000000,224.000000,102.00000,1940.000000,-37.862950,144.933500,4385.000000
50%,3.000000,8.700000e+05,10.300000,3103.000000,3.000000,2.000000,2.000000,521.000000,136.00000,1970.000000,-37.807600,145.007800,6763.000000
75%,4.000000,1.295000e+06,14.000000,3156.000000,4.000000,2.000000,2.000000,670.000000,188.00000,2000.000000,-37.754100,145.071900,10412.000000
max,16.000000,1.120000e+07,48.100000,3978.000000,30.000000,12.000000,26.000000,433014.000000,44515.00000,2106.000000,-37.390200,145.526350,21650.000000

# 4) Drop address, date, postcode, YearBuilt, lattitude, longtitude columns

In [154]:
data.drop(["Address","Date","Postcode","YearBuilt","Lattitude","Longtitude"],axis=1,inplace=True)

In [156]:
data

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.0,79.0,Yarra City Council,Northern Metropolitan,4019.0
3,Abbotsford,3,u,NaN,VB,Rounds,2.5,3.0,2.0,1.0,0.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.0,150.0,Yarra City Council,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.0,NaN,Maribyrnong City Council,Western Metropolitan,6543.0
34853,Yarraville,2,h,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.0,104.0,Maribyrnong City Council,Western Metropolitan,6543.0
34854,Yarraville,2,t,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.0,120.0,Maribyrnong City Council,Western Metropolitan,6543.0
34855,Yarraville,3,h,1140000.0,SP,hockingstuart,6.3,NaN,NaN,NaN,NaN,NaN,Maribyrnong City Council,Western Metropolitan,6543.0
34856,Yarraville,2,h,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.0,103.0,Maribyrnong City Council,Western Metropolitan,6543.0

# 5) Find the count of null value in each column

In [159]:
data.isnull().any()

Suburb           False
Rooms            False
Type             False
Price             True
Method           False
SellerG          False
Distance          True
Bedroom2          True
Bathroom          True
Car               True
Landsize          True
BuildingArea      True
CouncilArea       True
Regionname        True
Propertycount     True
dtype: bool

# 6) Fill the null value of property count, distance, Bedroom2, Bathroom, Car with 0

In [162]:
data[["Propertycount","Distance","Bedroom2","Bathroom","Car"]]=data[["Propertycount","Distance","Bedroom2","Bathroom","Car"]].fillna(0)

In [164]:
data

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.0,79.0,Yarra City Council,Northern Metropolitan,4019.0
3,Abbotsford,3,u,NaN,VB,Rounds,2.5,3.0,2.0,1.0,0.0,NaN,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.0,150.0,Yarra City Council,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.0,NaN,Maribyrnong City Council,Western Metropolitan,6543.0
34853,Yarraville,2,h,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.0,104.0,Maribyrnong City Council,Western Metropolitan,6543.0
34854,Yarraville,2,t,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.0,120.0,Maribyrnong City Council,Western Metropolitan,6543.0
34855,Yarraville,3,h,1140000.0,SP,hockingstuart,6.3,0.0,0.0,0.0,NaN,NaN,Maribyrnong City Council,Western Metropolitan,6543.0
34856,Yarraville,2,h,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.0,103.0,Maribyrnong City Council,Western Metropolitan,6543.0

# 7) Fill Null value of land size and bidding area columns with Mean

In [167]:
m=data[["Landsize","BuildingArea"]].mean()
m

Landsize        593.598993
BuildingArea    160.256400
dtype: float64

In [169]:
data[["Landsize","BuildingArea"]]=data[["Landsize","BuildingArea"]].fillna(m)

In [171]:
data

,Suburb,Rooms,Type,Price,Method,SellerG,Distance,Bedroom2,Bathroom,Car,Landsize,BuildingArea,CouncilArea,Regionname,Propertycount
0,Abbotsford,2,h,NaN,SS,Jellis,2.5,2.0,1.0,1.0,126.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
1,Abbotsford,2,h,1480000.0,S,Biggin,2.5,2.0,1.0,1.0,202.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
2,Abbotsford,2,h,1035000.0,S,Biggin,2.5,2.0,1.0,0.0,156.000000,79.0000,Yarra City Council,Northern Metropolitan,4019.0
3,Abbotsford,3,u,NaN,VB,Rounds,2.5,3.0,2.0,1.0,0.000000,160.2564,Yarra City Council,Northern Metropolitan,4019.0
4,Abbotsford,3,h,1465000.0,SP,Biggin,2.5,3.0,2.0,0.0,134.000000,150.0000,Yarra City Council,Northern Metropolitan,4019.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34852,Yarraville,4,h,1480000.0,PI,Jas,6.3,4.0,1.0,3.0,593.000000,160.2564,Maribyrnong City Council,Western Metropolitan,6543.0
34853,Yarraville,2,h,888000.0,SP,Sweeney,6.3,2.0,2.0,1.0,98.000000,104.0000,Maribyrnong City Council,Western Metropolitan,6543.0
34854,Yarraville,2,t,705000.0,S,Jas,6.3,2.0,1.0,2.0,220.000000,120.0000,Maribyrnong City Council,Western Metropolitan,6543.0
34855,Yarraville,3,h,1140000.0,SP,hockingstuart,6.3,0.0,0.0,0.0,593.598993,160.2564,Maribyrnong City Council,Western Metropolitan,6543.0
34856,Yarraville,2,h,1020000.0,PI,RW,6.3,2.0,1.0,0.0,250.000000,103.0000,Maribyrnong City Council,Western Metropolitan,6543.0

# 8) Find the unique value in method column

In [174]:
data["Method"].unique()

array(['SS', 'S', 'VB', 'SP', 'PI', 'SN', 'W', 'PN', 'SA'], dtype=object)

# 9) Create a dummy data for categorical data

In [177]:
data = pd.get_dummies(data, drop_first=True)

In [183]:
print(data.isnull().sum())

Rooms                                    0
Price                                    0
Distance                                 0
Bedroom2                                 0
Bathroom                                 0
                                        ..
Regionname_Northern Victoria             0
Regionname_South-Eastern Metropolitan    0
Regionname_Southern Metropolitan         0
Regionname_Western Metropolitan          0
Regionname_Western Victoria              0
Length: 795, dtype: int64

In [181]:
data = data.dropna(subset=['Price'])

# Part-2: Working with Model

# 1) Create the target data and feature data where target data is price

In [185]:
x=data.drop("Price",axis=1)
y=data["Price"]

In [187]:
x=x.fillna(0)
y=y.fillna(0)

In [189]:
from sklearn.model_selection import train_test_split

In [190]:
# split data
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

# 2) Create a linear regression model for Target and feature data

In [194]:
from sklearn.linear_model import LinearRegression,Ridge,Lasso

In [196]:
lr=LinearRegression()

In [198]:
lr

LinearRegression()

In [200]:
lr.fit(x_train,y_train)

LinearRegression()

In [201]:
#prediction
ypri=lr.predict(x_test)

# 3) Check if the model is overfitting or underfitting or it is accurate

In [205]:
train_score=lr.score(x_train,y_train)
test_score=lr.score(x_test,y_test)
print ("train score :" ,train_score)
print("test score : ",test_score)

train score : 0.6848643213384157
test score :  -14123426579.175844

# 4) If the model is overfitting then apply ridge and lasso regression algorithms

In [208]:
ridge = Ridge(alpha=1.0)
ridge.fit(x_train, y_train)

Ridge()

In [210]:
lasso = Lasso(alpha=0.1)
lasso.fit(x_train, y_train)

C:\Users\HP\anaconda3\Lib\site-packages\sklearn\linear_model\_coordinate_descent.py:697: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.400e+15, tolerance: 8.882e+11
  model = cd_fast.enet_coordinate_descent(

Lasso(alpha=0.1)

# model is underfitting that's why i use decision tree

In [215]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import numpy as np

# Create model
dt = DecisionTreeRegressor(max_depth=5, random_state=42)

# Train model
dt.fit(x_train, y_train)

# Prediction
y_pred_dt = dt.predict(x_test)

# Scores
train_score = dt.score(x_train, y_train)
test_score = dt.score(x_test, y_test)

print("Train Score:", train_score)
print("Test Score:", test_score)

Train Score: 0.6226208787239017
Test Score: 0.5950356192547761

# 5) Extract slope and intercept value from the model

In [224]:
# Intercept (c)
print("Intercept:", lr.intercept_)

# Slopes (m values for each feature)
print("Coefficients:", lr.coef_)

Intercept: -1440602040272.1348
Coefficients: [ 2.63925573e+05 -4.63978288e+04 -8.51983932e+04  1.30454822e+05
  4.18859265e+04  8.56571943e+00  3.62302316e+01 -4.64919709e+08
  5.44519609e+11  1.43763009e+12 -7.62718078e+11 -7.58003927e+12
 -6.29750864e+11 -1.56554828e+12  2.05585421e+12  3.13865194e+12
  1.97728246e+12 -1.05003845e+12 -1.56839346e+12  2.88027589e+12
 -1.28754642e+12 -2.28508976e+12 -2.35345562e+11 -5.05464206e+11
  4.05410868e+11  1.92021656e+12 -9.17404342e+10 -6.70433975e+11
 -7.73253332e+12 -6.48073264e+10  9.24076699e+11  1.63072534e+12
 -2.22282821e+12 -1.43596416e+12 -2.06779021e+12  1.28577278e+12
 -2.13258558e+11  1.80788908e+12  2.39733795e+12  4.33791271e+12
  1.02455549e+13  1.23473524e+11  1.85097958e+12  5.27817819e+11
  1.23449580e+12 -2.06055457e+11  3.80376015e+12 -8.10358563e+10
  1.33584857e+12 -4.10242685e+11  2.08684110e+12  3.70939937e+12
  2.01662627e+12  1.87641685e+12 -1.70927771e+12 -1.19834768e+12
 -1.78550065e+12 -4.75401303e+12 -4.03385243e+12  3.06511546e+12
  3.51286409e+11 -3.33765361e+12 -5.00294405e+11 -1.66487742e+12
 -9.04477658e+11 -8.67749027e+11 -9.90753335e+11  1.07688806e+12
 -4.02405338e+11  1.44060254e+12  7.58284895e+11 -1.18851797e+12
  1.74039225e+12  2.94880153e+10  2.87481041e+12  1.93711163e+12
 -6.23553169e+11 -9.51502990e+11  3.44252179e+11 -4.79120433e+11
  2.45684758e+12  1.58651789e+12 -1.96522505e+12  2.67697829e+11
 -5.83105626e+11  3.32769974e+12 -2.19799586e+11 -2.80443212e+11
 -8.91063260e+12  6.52650815e+11 -4.95139343e+11  3.68739778e+12
  2.61547437e+12 -9.91837792e+11 -7.22749503e+09  2.48267143e+11
  4.02621341e+11  7.09095637e+12 -9.10222451e+10 -1.12221416e+12
 -6.56364706e+11 -1.36536719e+12 -1.34640748e+12  1.64855823e+12
 -3.10292137e+12 -2.50782406e+12 -3.02946387e+12  9.24261072e+11
  1.51429787e+12  3.18524202e+11 -6.14178828e+11 -2.29177269e+12
  1.32430652e+12 -2.98263208e+11 -5.87443434e+11  2.78446231e+11
  3.48958716e+12  2.83504615e+11  6.80257298e+12  2.46574145e+12
  3.38209822e+12  4.95411814e+11  1.67134561e+12 -2.01904452e+12
  2.20818556e+12 -1.19672057e+09 -3.64593025e+11  1.51538523e+12
  4.69039157e+12  2.53130427e+12 -4.92581286e+12 -1.46990365e+12
  2.63711196e+11 -1.73296894e+12  4.13416458e+12  4.35263335e+11
  1.00521027e+11 -3.26874877e+12  5.77590177e+10 -1.21267427e+12
  2.23719455e+12  1.44060177e+12  4.30773314e+12 -1.70056872e+12
  8.39645245e+11 -4.42345488e+12  2.55903482e+11  1.44060276e+12
  1.23356595e+12  3.23045011e+12  2.42383138e+12 -1.18117287e+12
 -5.13524619e+11 -1.88384939e+12 -3.31859174e+12  4.46638300e+12
  3.55410453e+11  2.13426261e+12  4.13517381e+12 -3.20257604e+12
 -3.76941468e+12 -1.26787665e+12  2.14142121e+12  4.16480683e+11
 -6.11483318e+12 -1.92838477e+12  1.32668570e+12 -1.13635957e+11
  1.76771463e+11  2.55083044e+12  3.07128121e+11 -3.89722270e+11
 -1.06104314e+12 -2.13170393e+12  2.78422065e+12  2.81072087e+12
  2.68379769e+12  1.01983841e+12  9.37493372e+11 -8.21623682e+10
 -8.66946596e+10 -2.16839483e+12 -3.27350921e+12 -1.07586474e+12
  4.02044229e+12  2.16308850e+12  2.75698230e+11 -6.36927941e+10
 -1.08676720e+12 -5.58153154e+11  5.41458945e+10  9.71432595e+11
 -1.38059617e+12 -1.12535542e+12  1.03231943e+12  2.09660413e+12
 -1.46468093e+12  3.82218314e+11 -1.73187295e+12 -3.07561712e+11
 -1.93608954e+12 -1.23826450e+12  6.63227361e+11 -3.63356688e+12
  9.90589424e+11 -2.96361148e+12  5.32632532e+12  5.23013730e+11
  1.14845910e+12  2.19563237e+12 -2.58206197e+12 -8.35590902e+12
 -3.29306689e+12 -2.78205446e+11 -1.64324516e+12  2.75013114e+11
  2.07635723e+11  3.52621190e+11  2.06703393e+12  6.71968237e+12
 -1.48704592e+12 -9.67265665e+11  2.15846774e+12  1.31655648e+12
 -2.24416803e+11 -4.11056821e+12  4.18428660e+11 -8.16630282e+12
 -1.91754212e+12  2.38935656e+12 -1.31933457e+12 -1.09720719e+12
  3.24960534e+12 -2.80664183e+11  2.72452797e+12  7.63339241e+12
  1.86815479e+12  1.48678211e+11 -3.39283822e+11  3.22625565e+12
 -8.31739510e+12  1.30338178e+12  6.97481643e+11 -3.05870193e+12
  2.14744318e+12  8.92279437e+11  1.93830454e+12  1.75666437e+12
  1.41275548e+12  2.68986181e+12 -3.21120973e+12  5.80492027e+11
 -6.09391159e+12 -2.13166626e+12 -2.44641693e+12  1.68204335e+11
 -1.23325925e+12 -5.35671012e+10  9.01691275e+11  5.56200742e+12
  8.16767907e+11 -3.41053016e+11 -3.84648980e+12  9.66727700e+09
 -8.40194562e+10 -9.58872823e+11  7.09247736e+11  8.63482180e+12
 -2.28960122e+11  4.18364860e+12 -1.39987279e+12  1.35696478e+12
  7.47202571e+12  5.08157248e+12 -2.76766157e+12 -2.76209364e+11
 -1.84670815e+12 -4.90093524e+10 -8.72327718e+12 -1.40147638e+12
  3.08641838e+12 -3.92011038e+12  2.59192829e+12 -3.89862914e+12
  8.81757550e+11  3.17792102e+11  4.24915589e+11 -9.43599122e+11
 -1.25737124e+10 -9.55128438e+11 -1.76891197e+12 -3.41743714e+12
  4.87955554e+10 -6.34195856e+12 -3.10773658e+12  1.15354559e+13
  8.51952138e+12  1.59911381e+11 -1.04552741e+11 -1.66575312e+12
  4.88280210e+12  1.86600401e+12 -2.94943936e+12  1.35394465e+12
  8.00183225e+09  9.49077105e+12  1.00173061e+11  3.14965843e+11
  1.49865136e+12 -1.69414442e+11  4.67072747e+10 -1.79295004e+12
  3.20585892e+11  8.35210987e+11 -1.57736503e+12  1.15187846e+12
  7.88310952e+11  7.78936979e+10 -3.11424541e+12  1.53035194e+12
 -4.61419547e+11  3.16243798e+11  1.05004504e+12 -1.13225077e+11
 -7.76773257e+11 -1.95178011e+12  1.18474942e+12  2.69495585e+12
  5.62294626e+11  3.46065341e+10  1.81390333e+12  2.58474030e+12
 -8.00319241e+11 -3.15406267e+12 -1.21865080e+12 -4.14805425e+12
 -4.56043820e+12 -1.40270345e+12  9.99357630e+11 -6.13483533e+12
  2.72724422e+11 -3.77781953e+11  1.03026299e+12 -8.18768261e+12
 -1.75440229e+12  2.09923108e+11 -5.58715975e+12  2.55750266e+12
 -3.58197976e+10 -7.06862798e+12 -5.44581758e+12 -3.79035984e+12
 -4.07012636e+12 -4.59437737e+12 -1.38790542e+12  9.63130307e+11
  1.64855818e+12  2.69495614e+12 -2.71636529e+05 -4.77413838e+05
  5.17479301e+10  7.31144922e+04  6.10953911e+04  2.05466761e+11
  3.97424095e+04 -2.02768255e+11  7.59691895e+03  1.70283724e+11
  7.96304306e+10 -8.87769127e+04  1.00106473e+05  5.78332404e+05
  2.41980032e+05 -2.89013504e+05  1.33645435e+11  9.02371688e+04
 -9.43142501e+04 -1.76799623e+05  6.63201574e+04 -2.19445177e+05
  1.58151004e+05  1.46764796e+05 -1.07951224e+05  9.70121764e+03
 -4.80271947e+04  5.26600151e+05  1.32875233e+05  1.58252821e+03
  3.15913449e+05  1.43027697e+05  5.00072144e+04  3.71369614e+05
 -4.29125911e+04 -1.35233111e+04 -5.59694625e+04  5.70323740e+04
  2.04167203e+05  1.24819534e+05 -2.60080419e+05 -6.00274341e+04
  5.45396928e+04  1.58412922e+05  7.72076889e+04  8.08258311e+05
  8.90246330e+04 -7.63493695e+04  9.22964458e+04 -2.41186190e+05
 -5.29648448e+04  4.71013279e+04  1.22367961e+11  9.22170521e+04
  6.80040525e+04  5.50828701e+04  1.32795927e+05 -1.80000761e+05
 -4.92589471e+04  6.20032167e+04 -3.13054901e+04  3.11802925e+05
  3.40652356e+05 -1.44713180e+05  5.26017412e+04 -1.49325001e+05
  5.22889103e+05  9.55180532e+04 -3.48275171e+08  1.69999783e+05
  1.74683675e+05  5.99653862e+05  9.47062725e+04 -2.55580247e+05
 -6.63654545e+03 -3.04208828e+05  4.95978994e+04 -3.77862899e+05
  4.58267952e+04 -9.38330845e+04  1.48094254e+07  2.36086279e+05
 -2.61145098e+04  1.87022073e+05  1.34520617e+06  2.52848129e+05
  6.28075712e+04  3.10815762e+05 -6.06463736e+04  1.73708505e+05
 -4.17895202e+05 -4.77074321e+04 -4.75193846e+04  6.97791421e+04
  4.62059884e+04 -2.01648090e+05  1.90504541e+06  1.43037813e+05
 -2.12564860e+05  4.40311924e+04 -3.52103405e+04 -5.74844403e+05
 -1.71271626e+05 -6.29810873e+04 -1.18397334e+05  2.68975755e+04
  5.79590128e+04  3.38304445e+05 -6.36241913e+00  1.67233575e+04
  7.29646777e+04  8.35020476e+04  1.26587102e+05  1.62231476e+05
  4.80223545e+04 -1.61270863e+05 -7.82931529e+04  2.31445312e-01
  1.59546056e+06  2.36328125e-01  4.84494255e+04  8.75424420e+04
 -1.10994792e+04  6.30423693e+04 -2.02581013e+04 -2.66308311e+05
 -1.83593438e+05  7.24275271e+03 -4.66824036e+05 -1.61673117e+05
 -2.44140625e-04  0.00000000e+00  7.75395504e+04  1.32870595e+05
  6.09100350e+04  5.36396963e+05  2.46383490e+04  8.97562749e+05
 -5.35051731e+04 -2.21249307e+05  4.60476338e+04  1.52349472e-04
 -8.61783633e+04 -4.88536833e+04 -7.16287068e+04 -4.75198030e-05
  1.44829885e+04  3.32872780e+04  6.19263508e+04 -1.98094281e+05
  5.95717081e+05  1.35102872e+05  1.10756542e+05  1.16238035e+05
  2.54174722e+04 -2.49889781e-04 -3.35377429e+03 -5.71252036e+04
  8.03516278e+04  1.21616729e+05  3.05966144e+04  9.16611166e+04
  9.84482189e+04 -2.76032719e-04  1.32414698e+05  2.59028570e+04
  8.67642394e+04  3.18758772e-04 -1.89063588e+05 -2.18108492e+05
  1.05532215e+05  4.01067295e+05 -2.06413388e-05 -3.42841424e+05
  4.93990209e+05  2.11715932e+05  2.56768206e+05  3.64248681e+05
 -5.24676429e+04 -1.03385537e-06  7.79560187e+04 -8.53051419e+04
  3.86177380e+04 -7.43366020e+04  4.91425999e+05  8.38265987e-06
 -2.33959749e+05  1.42419067e+05 -3.01184278e+04 -7.15193820e+04
  1.40770718e+05 -2.26484017e+04 -4.44757399e+04  3.22456614e+05
  7.08527763e+04  2.81509297e+05 -5.64659325e+05 -2.42438411e+03
  1.00889942e+05 -4.85678206e+04  5.99372434e+04  1.65909296e-06
 -4.42543664e+04 -1.92490054e+05  7.06982973e-07 -1.80479472e+04
 -1.19255128e-05  3.67853520e+05 -3.20986146e-07 -1.33822052e+05
  5.35499986e+04  2.64742746e+05  1.53250365e+05 -4.69783800e+04
  8.14612890e+04 -5.17931767e-06 -2.16726591e+05 -5.91220684e+04
  7.55147787e+03  1.32120002e+05  4.16357787e+04 -9.17590282e+04
  1.40627160e+05  1.11596557e+05 -9.11939424e-06 -9.09077463e+04
  1.28695081e+05  2.73968964e+04 -3.09557072e-06  2.06258889e+05
  8.41035414e+04 -1.81033274e+05  6.73824542e+04  3.98472280e+04
  1.20128854e+05 -1.98223106e+05  5.49714041e+04 -2.60029981e+04
  9.19452845e+04  8.60048114e+05  1.60352510e+05 -5.25709477e+04
  1.93360714e+05  8.29565138e+03  1.33535650e-06  5.11441408e+04
 -1.93547449e+05  1.05221849e+05  3.44330246e+05  6.55355995e+04
 -2.83856537e+04  6.64347133e+04  1.43466031e+04 -2.65281254e+04
 -2.82169427e+05  1.25457122e+05 -1.06576060e+04  3.70825821e+04
 -4.58129944e-06  2.09947248e+04  7.56135507e+04  3.19022123e+05
  2.30985631e+05 -2.15088949e-06  3.18624174e+05 -8.43196176e-07
  4.12359667e+05 -2.50430570e+04  7.96390108e+04  4.82109375e+04
  7.84957093e+04 -1.07576803e+05  1.95629112e+05  6.07194816e+04
 -6.41471463e+04  2.00947137e+05 -5.85005911e+05 -3.84630328e+05
 -2.80969560e+04  1.84454257e-06  3.09714233e-06  1.66648906e+04
  5.88352118e+04  9.15203853e+03  2.50023449e+05  3.97151665e+04
  3.24689681e+04 -1.69804699e+05  4.83007224e+03  1.31968409e-06
 -8.58977548e+04 -5.08531317e+05  3.49975261e+05  2.30831853e+05
  4.03151148e+04  1.01802143e+05  5.19426528e+04  2.09869583e+04
  5.01086696e+04 -1.30622791e+04 -3.87239429e+04  2.30330381e+05
 -2.07158412e+05  3.68303893e+05 -3.82944493e+05  2.01742838e+05
  3.77418473e-07 -2.21351911e-07  1.39525748e+05  8.07642979e+04
 -5.61517235e+05  1.38026847e+05 -3.86114033e+05 -2.25740467e+04
 -6.07276837e+04 -2.79803442e+05 -2.11293809e-08 -1.11638201e-08
  2.09406554e+04 -3.89991328e-09  1.18990230e+06  5.81161638e+04
  1.51733787e+05  2.12457962e-09 -3.99942481e+04 -2.86490831e-11
 -3.20142135e-10  3.37865828e+04 -2.88597140e+05  8.73114914e-11
  5.71804412e+04 -5.36740018e+04  1.08172193e+05  5.46826362e+05
 -1.56927293e+05  0.00000000e+00  7.92453421e+04 -1.55915197e+05
 -8.75997140e+04 -4.87124138e+05 -6.88769027e+04  1.36950056e+05
  1.30720202e+05 -1.44051985e+05  4.02006973e+04  2.91294218e+05
  2.48584129e+05 -1.99389433e+04  7.72894012e+05 -1.50666906e+05
  0.00000000e+00  0.00000000e+00  0.00000000e+00 -2.78307857e+05
  9.69191117e+04 -7.71927743e+04  6.24524070e+05  1.30162859e+05
  4.43442955e+04  0.00000000e+00  0.00000000e+00  0.00000000e+00
  9.30905418e+05  2.21700345e+05 -1.34841819e+05 -8.60318354e+04
  2.76644459e+05  1.32781546e+04  7.64417366e+04  1.02645695e+05
  6.81537428e+04 -2.65863777e+04  5.76311149e+03  3.31621560e+04
 -1.62947544e+04 -3.03902718e+05  5.67403467e+04  1.52467008e+04
  1.10834098e+05  1.20225332e+03  1.60664750e+05  2.32626775e+05
 -8.19875131e+04  0.00000000e+00  0.00000000e+00 -8.74521673e+04
  0.00000000e+00  6.32712161e+05  1.06740442e+05  2.42381400e+05
  4.59410857e+04  0.00000000e+00  0.00000000e+00  0.00000000e+00
  1.69226124e+05 -1.01294721e+05  0.00000000e+00  2.00688382e+12
  3.50437848e+12 -5.26181662e+11  1.28454060e+12 -3.53429890e+12
 -2.63736635e+12 -2.49714861e+12  1.55968851e+12 -3.64536718e+12
 -1.76309674e+12 -5.11090407e+12 -5.64762568e+12  2.14842377e+12
  2.27197016e+12  3.17215662e+12 -9.29427436e+10  5.33621231e+12
 -3.81629936e+12 -5.20178679e+11  1.10356733e+11  4.42846426e+12
 -1.99893024e+12 -1.67571667e+12  2.09556144e+12  5.19732825e+11
  9.90287310e+12  4.61464233e+12  2.24570982e+12  1.58182941e+12
  4.34475208e+12 -3.36234002e+12  7.45763536e+11  2.67621987e+12
  6.67145491e+12  2.62205190e+12  8.63650770e+12  6.42706015e+11
  3.61238461e+12  5.12153847e+12]

# 6) Display Mean Squared Error

In [227]:
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

In [229]:
mse = mean_squared_error(y_test, ypri)
print("MSE:", mse)

MSE: 6.035077219175454e+21

# 7) Display Mean Absolute Error

In [234]:
mae = mean_absolute_error(y_test, ypri)
print("MAE:", mae)

MAE: 2728602058.866733

# 8) Display Root mean Squared error

In [237]:
rmse = np.sqrt(mse)
print("RMSE:", rmse)

RMSE: 77685759436.17628

# 9) Display R2 score

In [240]:
r2 = r2_score(y_test, ypri)
print("R2 Score:", r2)

R2 Score: -14123426579.175844